# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        MainWindow.setStyleSheet("QPushButton {\n"
"background-color:#ff5500;\n"
"border-radius:10px;\n"
"color:white;\n"
"font-size:14px;\n"
"}\n"
"QPushButton:pressed   {\n"
"background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"border-radius:10px;\n"
"color:black;\n"
"font-size:14px;\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"border-radius:10px;\n"
"border:none;\n"
"padding: 0 8px;\n"
"}\n"
"QLineEdit::hover{\n"
"border:2px solid gray;\n"
"padding: 0 8px;\n"
"border-radius:10px;\n"
"border:none;\n"
"background-color:#bcbcbc;\n"
"color:black;\n"
"}\n"
"\n"
"QCheckBox{\n"
"spacing:5px;\n"
"\n"
"}\n"
"QCheckBox::indicator {\n"
"    width: 23px;\n"
"    height: 23px;\n"
"}\n"
"\n"
"")     
      
#        label = QLabel(self)
#        pixmap = QPixmap('cat.jpg')
#        label.setPixmap(pixmap)
#        self.setCentralWidget(label)
#        self.resize(pixmap.width(), pixmap.height())
    
    
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1366, 768))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 310, 768))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 211))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.textbox_1 = QtWidgets.QLineEdit(self.groupBox)
        self.textbox_1.setGeometry(QtCore.QRect(10, 30, 271, 30))
        self.textbox_1.setObjectName("textbox_1")
        self.textbox_2 = QtWidgets.QLineEdit(self.groupBox)
        self.textbox_2.setGeometry(QtCore.QRect(10, 80, 271, 30))
        self.textbox_2.setObjectName("textbox_2")
        self.button_1 = QtWidgets.QPushButton(self.groupBox)
        self.button_1.setGeometry(QtCore.QRect(20, 160, 101, 41))
        self.button_1.setStyleSheet("")
        self.button_1.setObjectName("button_1")
        self.button_2 = QtWidgets.QPushButton(self.groupBox)
        self.button_2.setGeometry(QtCore.QRect(170, 160, 101, 41))
        self.button_2.setStyleSheet("")
        self.button_2.setObjectName("button_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 250, 291, 211))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.textbox_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.textbox_3.setGeometry(QtCore.QRect(10, 30, 271, 30))
        self.textbox_3.setObjectName("textbox_3")
        self.button_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.button_4.setGeometry(QtCore.QRect(170, 160, 101, 41))
        self.button_4.setStyleSheet("")
        self.button_4.setObjectName("button_4")
        self.button_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.button_3.setGeometry(QtCore.QRect(170, 90, 101, 41))
        self.button_3.setStyleSheet("")
        self.button_3.setObjectName("button_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(20, 110, 91, 51))
        self.checkBox.setObjectName("checkBox")
#        self.progressBar = QtWidgets.QProgressBar(self.widget)
#        self.progressBar.setGeometry(QtCore.QRect(1090, 700, 271, 23))
#        self.progressBar.setProperty("value", 24)
#        self.progressBar.setObjectName("progressBar")
#        self.label = QtWidgets.QLabel(self.widget)
#        
#        self.label.setPixmap(QtGui.QPixmap("mapsPY.png"))
#        self.label.setGeometry(QtCore.QRect(310, 0, 1056, 768))
#        self.label.setAlignment(QtCore.Qt.AlignCenter)
#        self.label.setObjectName("label")
#        
#        self.label =  QtWidgets.QLabel(self.widget)
#        self.label.setPixmap(QPixmap("mapsPY.png"))
#        self.label.setGeometry(10,10,400,400)
      
        
        self.label = QtWidgets.QLabel(self.widget)
        pixmap = QtGui.QPixmap('mapsPY.png')
        self.label.setPixmap(pixmap)
        self.label.setGeometry(QtCore.QRect(310, 0, 1056, 768))
       
        
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1366, 21))
        self.menubar.setObjectName("menubar")
        self.qmenu_menu = QtWidgets.QMenu(self.menubar)
        self.qmenu_menu.setObjectName("qmenu_menu")
        self.qmenu_ayarlar = QtWidgets.QMenu(self.menubar)
        self.qmenu_ayarlar.setObjectName("qmenu_ayarlar")
        self.qmenu_cikis = QtWidgets.QMenu(self.menubar)
        self.qmenu_cikis.setObjectName("qmenu_cikis")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.qmenu_menu.menuAction())
        self.menubar.addAction(self.qmenu_ayarlar.menuAction())
        self.menubar.addAction(self.qmenu_cikis.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Location"))
        self.button_1.setText(_translate("MainWindow", "PushButton"))
        self.button_2.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Visualization"))
        self.button_4.setText(_translate("MainWindow", "PushButton"))
        self.button_3.setText(_translate("MainWindow", "PushButton"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.qmenu_menu.setTitle(_translate("MainWindow", "Menü"))
        self.qmenu_ayarlar.setTitle(_translate("MainWindow", "Ayarlar"))
        self.qmenu_cikis.setTitle(_translate("MainWindow", "Çıkış"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
